on:
jobs:
name: Backend CI


  pull_request:
    branches: [dev, staging, production]
  push:
    branches: [dev]


  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-4{{ runner.os }}-4{{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-4{{ runner.os }}-

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
